/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IndicadoresRouteImport } from './routes/indicadores'
import { Route as MapasMunicipaisRouteImport } from './routes/mapas-municipais'
import { Route as MetodologiaRouteImport } from './routes/metodologia'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicadoresRoute = IndicadoresRouteImport.update({
  id: '/indicadores',
  path: '/indicadores',
  getParentRoute: () => rootRouteImport,
} as any)
const MapasMunicipaisRoute = MapasMunicipaisRouteImport.update({
  id: '/mapas-municipais',
  path: '/mapas-municipais',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/indicadores': typeof IndicadoresRoute
  '/mapas-municipais': typeof MapasMunicipaisRoute
  '/metodologia': typeof MetodologiaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/indicadores': typeof IndicadoresRoute
  '/mapas-municipais': typeof MapasMunicipaisRoute
  '/metodologia': typeof MetodologiaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/indicadores': typeof IndicadoresRoute
  '/mapas-municipais': typeof MapasMunicipaisRoute
  '/metodologia': typeof MetodologiaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/indicadores' | '/mapas-municipais' | '/metodologia'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/indicadores' | '/mapas-municipais' | '/metodologia'
  id: '__root__' | '/' | '/indicadores' | '/mapas-municipais' | '/metodologia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IndicadoresRoute: typeof IndicadoresRoute
  MapasMunicipaisRoute: typeof MapasMunicipaisRoute
  MetodologiaRoute: typeof MetodologiaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicadores': {
      id: '/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof IndicadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapas-municipais': {
      id: '/mapas-municipais'
      path: '/mapas-municipais'
      fullPath: '/mapas-municipais'
      preLoaderRoute: typeof MapasMunicipaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologia': {
      id: '/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof MetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IndicadoresRoute: IndicadoresRoute,
  MapasMunicipaisRoute: MapasMunicipaisRoute,
  MetodologiaRoute: MetodologiaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
