import { useEffect, useMemo, useRef, useState } from "react";
import { motion, useMotionValue, animate } from "motion/react";
import type { Municipality } from "@/lib/ranking-data";
import { normalizeSearch } from "@/lib/search";

type Props = {
  top: Municipality[];
  bottom: Municipality[];
  selectedIbge: string;
  onSelect: (m: Municipality) => void;
};

// One row of the full-dataset export (all 5.570 municípios), used so the
// search box can find any municipality, not just the top/bottom 15 mocked
// on the rail. Generated by scripts/export_ranking_frontend.py from the
// real fato_indicadores.parquet.
type RealMunicipio = {
  codibge: string;
  name: string;
  uf: string;
  region: string;
  rank: number;
  composite: number;
  population: number | null;
};

type SearchableMunicipio = {
  codibge: string;
  name: string;
  uf: string;
  region: string;
  rank: number;
  composite: number;
};

// Focus card (current municipality) beside a vertical drag rail: a crescent
// ("meia lua") of small dots, one per ranked municipality, that curves
// toward whichever one is in focus. Dragging/scrolling the rail moves
// through the ranking one position at a time; "município anterior/posterior"
// captions above and below give a positional reference without needing a
// full visible list. A search box jumps straight to a name.

const DOT_GAP = 16; // px, vertical space per position along the rail
const RAIL_HEIGHT = 460; // px, visible window height of the rail
const CURVE_SPREAD = 10; // how many positions the crescent bulge extends over
const CURVE_AMPLITUDE = 34; // px, how far the crescent bulges at the focus dot
const TOP_COLOR = "var(--color-brand)";
const BOTTOM_COLOR = "var(--color-accent-warm)";

export function RouletteRanking({
  top,
  bottom,
  selectedIbge,
  onSelect,
}: Props) {
  const items = useMemo(() => {
    return [
      ...top.map((m) => ({ m, band: "top" as const })),
      ...bottom.map((m) => ({ m, band: "bottom" as const })),
    ];
  }, [top, bottom]);

  const TOTAL = items[0]?.m.totalMunicipalities ?? 5570;

  // targetY(i): translateY needed so position i lands on the rail's center.
  const targetY = (i: number) => RAIL_HEIGHT / 2 - (i * DOT_GAP + DOT_GAP / 2);

  const [focusIndex, setFocusIndexState] = useState(() => {
    const idx = items.findIndex((it) => it.m.ibge === selectedIbge);
    return idx >= 0 ? idx : 0;
  });
  // Initialized to targetY(focusIndex) so the focused dot starts centered on
  // the rail instead of snapping there only after the first drag.
  const offset = useMotionValue(targetY(focusIndex));
  const [query, setQuery] = useState("");

  // Full 5.570-município dataset, fetched once so search finds any
  // municipality — not just the 30 mocked on the rail. Falls back to
  // searching just the rail's municípios while it's loading or if the
  // export is unavailable.
  const [fullDataset, setFullDataset] = useState<RealMunicipio[] | null>(null);
  useEffect(() => {
    let cancelled = false;
    fetch(`${import.meta.env.BASE_URL}data/ranking-composto-2023.json`)
      .then((r) => (r.ok ? r.json() : Promise.reject(r.status)))
      .then((data: RealMunicipio[]) => {
        if (!cancelled) setFullDataset(data);
      })
      .catch(() => {
        if (!cancelled) setFullDataset([]);
      });
    return () => {
      cancelled = true;
    };
  }, []);

  const [searchResult, setSearchResult] = useState<SearchableMunicipio | null>(
    null,
  );

  const goTo = (index: number, notify = true) => {
    const clamped = Math.max(0, Math.min(items.length - 1, index));
    animate(offset, targetY(clamped), {
      type: "spring",
      stiffness: 320,
      damping: 34,
    });
    setFocusIndexState(clamped);
    const item = items[clamped];
    if (notify && item) onSelect(item.m);
  };

  const snapToNearest = () => {
    const raw = offset.get();
    const idxFloat = (RAIL_HEIGHT / 2 - raw - DOT_GAP / 2) / DOT_GAP;
    goTo(Math.round(idxFloat));
  };

  // React attaches wheel listeners as passive by default, so preventDefault()
  // on a JSX onWheel handler is silently ignored and the page scrolls behind
  // the rail. A native, non-passive listener is required to actually trap
  // the scroll inside the rail.
  const railRef = useRef<HTMLDivElement>(null);
  const focusIndexRef = useRef(focusIndex);
  focusIndexRef.current = focusIndex;
  const goToRef = useRef(goTo);
  goToRef.current = goTo;

  useEffect(() => {
    const el = railRef.current;
    if (!el) return;
    const onWheelNative = (e: WheelEvent) => {
      e.preventDefault();
      goToRef.current(focusIndexRef.current + Math.sign(e.deltaY));
    };
    el.addEventListener("wheel", onWheelNative, { passive: false });
    return () => el.removeEventListener("wheel", onWheelNative);
  }, []);

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "ArrowDown") {
      e.preventDefault();
      goTo(focusIndex + 1);
    }
    if (e.key === "ArrowUp") {
      e.preventDefault();
      goTo(focusIndex - 1);
    }
  };

  const rankLabel = (i: number, band: "top" | "bottom") =>
    band === "top" ? `#${i + 1}` : `#${TOTAL - (items.length - 1 - i)}`;

  // Rail's own 30 municípios, normalized to the same shape as the full
  // dataset so search has one code path either way.
  const mockAsSearchable = useMemo<SearchableMunicipio[]>(
    () =>
      items.map((it, i) => ({
        codibge: it.m.ibge,
        name: it.m.name,
        uf: it.m.uf,
        region: it.m.region,
        rank: it.band === "top" ? i + 1 : TOTAL - (items.length - 1 - i),
        composite: it.m.composite,
      })),
    [items, TOTAL],
  );

  const searchPool = fullDataset ?? mockAsSearchable;
  const searchTotal = fullDataset?.length ?? TOTAL;

  const matches = useMemo(() => {
    const q = normalizeSearch(query);
    if (!q) return [];
    return searchPool
      .filter(
        (m) =>
          normalizeSearch(m.name).includes(q) || normalizeSearch(m.uf) === q,
      )
      .slice(0, 8);
  }, [searchPool, query]);

  const selectMatch = (m: SearchableMunicipio) => {
    setSearchResult(m);
    const localIndex = items.findIndex((it) => it.m.ibge === m.codibge);
    if (localIndex >= 0) goTo(localIndex);
    setQuery("");
  };

  const focused = items[focusIndex];
  const prev = items[focusIndex - 1];
  const next = items[focusIndex + 1];
  const focusColor = focused?.band === "top" ? TOP_COLOR : BOTTOM_COLOR;

  return (
    <div className="relative">
      {/* Search */}
      <div className="relative border-b border-border">
        <input
          type="text"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          onKeyDown={(e) => {
            if (e.key === "Enter" && matches.length > 0)
              selectMatch(matches[0]);
          }}
          placeholder={
            fullDataset === null
              ? "Carregando base completa de municípios…"
              : "Buscar entre os 5.570 municípios…"
          }
          aria-label="Buscar município"
          className="w-full px-4 py-3 bg-card font-mono text-xs uppercase tracking-widest placeholder:text-muted-foreground/70 placeholder:normal-case focus:outline-none focus:bg-brand-soft/40"
        />
        {query && (
          <div className="absolute left-0 right-0 top-full z-30 bg-card border border-t-0 border-border shadow-lg max-h-64 overflow-y-auto">
            {matches.length > 0 ? (
              matches.map((m) => (
                <button
                  key={m.codibge}
                  type="button"
                  onClick={() => selectMatch(m)}
                  className="w-full flex items-center justify-between gap-3 px-4 py-2.5 text-left hover:bg-brand-soft transition-colors"
                >
                  <span className="text-sm truncate">
                    {m.name}{" "}
                    <span className="text-muted-foreground">· {m.uf}</span>
                  </span>
                  <span className="font-mono text-[10px] text-muted-foreground shrink-0">
                    #{m.rank}
                  </span>
                </button>
              ))
            ) : (
              <div className="px-4 py-3 text-sm text-muted-foreground">
                Nenhum município encontrado.
              </div>
            )}
          </div>
        )}
      </div>

      {/* Search result: position + índice for any município (works even
          outside the top/bottom 15 shown on the rail below). */}
      {searchResult && (
        <div className="flex items-center justify-between gap-3 px-4 py-3 border-b border-border bg-brand-soft/40">
          <div className="min-w-0">
            <div className="text-sm font-semibold truncate">
              {searchResult.name}
              <span className="text-muted-foreground font-normal">
                {" "}
                · {searchResult.uf}
              </span>
            </div>
            <div className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">
              {searchResult.region}
            </div>
          </div>
          <div className="flex items-center gap-3 shrink-0">
            <div className="text-right">
              <div className="font-display text-2xl leading-none tabular-nums">
                {searchResult.composite.toFixed(1)}
              </div>
              <div className="font-mono text-[10px] text-muted-foreground">
                #{searchResult.rank} de {searchTotal}
              </div>
            </div>
            <button
              type="button"
              onClick={() => setSearchResult(null)}
              aria-label="Fechar resultado da busca"
              className="size-6 rounded-full border border-border hover:bg-card transition-colors text-xs"
            >
              ×
            </button>
          </div>
        </div>
      )}

      <div className="flex items-stretch gap-5 p-5">
        {/* Focus card: current municipality — name and rank only, the rest
            already lives in the detail panel on the right. */}
        <div className="w-36 shrink-0">
          <div className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">
            {focused?.band === "top" ? "Top 15" : "Bottom 15"}
          </div>
          <div
            className="font-display text-3xl leading-none mt-1"
            style={{ color: focusColor }}
          >
            {focused ? rankLabel(focusIndex, focused.band) : ""}
          </div>
          <div className="font-mono text-[10px] text-muted-foreground mt-0.5">
            de {TOTAL}
          </div>

          <div className="mt-6 text-lg font-semibold leading-snug">
            {focused?.m.name}
            <span className="text-muted-foreground font-normal text-sm">
              {" "}
              · {focused?.m.uf}
            </span>
          </div>
        </div>

        {/* Crescent drag rail */}
        <div className="flex-1 min-w-0 flex flex-col items-center">
          <div className="h-10 text-center">
            <div className="font-mono text-[9px] uppercase tracking-widest text-muted-foreground">
              Anterior
            </div>
            <div className="text-xs truncate max-w-40">
              {prev?.m.name ?? "—"}
            </div>
          </div>

          <div
            ref={railRef}
            className="relative w-full overflow-hidden select-none focus:outline-none"
            style={{ height: RAIL_HEIGHT }}
            onKeyDown={handleKeyDown}
            tabIndex={0}
            aria-label="Trilho de navegação do ranking"
          >
            {/* Backbone guide */}
            <div
              aria-hidden
              className="absolute left-1/2 top-0 bottom-0 w-px -translate-x-1/2 bg-border"
            />
            {/* Center focus ring, offset to align with the focus dot's curve bulge */}
            <div
              aria-hidden
              className="absolute top-1/2 -translate-y-1/2 size-6 rounded-full border border-dashed border-brand/50 z-20"
              style={{
                left: `calc(50% + ${CURVE_AMPLITUDE}px)`,
                transform: "translate(-50%, -50%)",
              }}
            />

            <motion.div
              drag="y"
              dragConstraints={{ top: 0, bottom: 0 }}
              dragElastic={0.2}
              onDrag={(_, info) => offset.set(offset.get() + info.delta.y)}
              onDragEnd={snapToNearest}
              className="absolute left-0 right-0 top-0 cursor-grab active:cursor-grabbing"
              style={{ y: offset }}
            >
              {items.map((it, i) => {
                const d = i - focusIndex;
                const absD = Math.abs(d);
                const isFocus = d === 0;
                const color = it.band === "top" ? TOP_COLOR : BOTTOM_COLOR;
                const t = Math.max(-1, Math.min(1, d / CURVE_SPREAD));
                const curveX = CURVE_AMPLITUDE * Math.cos(t * (Math.PI / 2));
                const fade = Math.max(0.15, 1 - absD / (CURVE_SPREAD + 2));
                const scale = isFocus
                  ? 1
                  : Math.max(0.4, 1 - (absD / (CURVE_SPREAD + 2)) * 0.7);
                return (
                  <div
                    key={it.m.ibge}
                    className="absolute left-1/2 flex items-center justify-center"
                    style={{
                      top: i * DOT_GAP,
                      height: DOT_GAP,
                      width: DOT_GAP,
                    }}
                  >
                    <motion.button
                      type="button"
                      onClick={() => goTo(i)}
                      aria-label={`${it.m.name} · ${rankLabel(i, it.band)}`}
                      animate={{ x: curveX, opacity: fade, scale }}
                      transition={{
                        type: "spring",
                        stiffness: 300,
                        damping: 30,
                      }}
                      className="rounded-full"
                      style={{
                        width: isFocus ? 14 : 8,
                        height: isFocus ? 14 : 8,
                        backgroundColor: color,
                        boxShadow: isFocus
                          ? `0 0 0 3px color-mix(in oklab, ${color} 25%, transparent)`
                          : undefined,
                      }}
                    />
                  </div>
                );
              })}
            </motion.div>

            {/* Fade masks so the rail reads as a continuous thread, not a hard crop */}
            <div className="pointer-events-none absolute inset-x-0 top-0 h-10 bg-gradient-to-b from-card to-transparent z-10" />
            <div className="pointer-events-none absolute inset-x-0 bottom-0 h-10 bg-gradient-to-t from-card to-transparent z-10" />
          </div>

          <div className="h-10 text-center">
            <div className="font-mono text-[9px] uppercase tracking-widest text-muted-foreground">
              Posterior
            </div>
            <div className="text-xs truncate max-w-40">
              {next?.m.name ?? "—"}
            </div>
          </div>
        </div>
      </div>

      {/* Nav helpers */}
      <div className="flex items-center justify-between gap-2 px-3 py-3 border-t border-border">
        <div className="flex gap-2">
          <button
            onClick={() => goTo(focusIndex - 1)}
            className="size-8 rounded-full border border-border bg-card hover:bg-brand-soft transition-colors font-mono text-xs"
            aria-label="Anterior"
          >
            ↑
          </button>
          <button
            onClick={() => goTo(focusIndex + 1)}
            className="size-8 rounded-full border border-border bg-card hover:bg-brand-soft transition-colors font-mono text-xs"
            aria-label="Próximo"
          >
            ↓
          </button>
          <button
            onClick={() => goTo(top.length)}
            className="px-3 h-8 rounded-full border border-border bg-card hover:bg-accent-warm-soft transition-colors font-mono text-[10px] uppercase tracking-widest"
          >
            Ir para piores
          </button>
        </div>
        <div className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground text-right">
          Arraste o trilho, role ou busque
        </div>
      </div>
    </div>
  );
}
